 - name: Maximize build disk space
  # You may pin to the exact commit or the version.
  # B
  uses: easimon/maximize-build-space@v10
  with:
    # Space to be left free on the root filesystem, in Megabytes.
    root-reserve-mb: # optional, default is 1024
    # Space to be left free on the temp filesystem (/mnt), in Megabytes.
    temp-reserve-mb: # optional, default is 100
    # Swap space to create, in Megabytes.
    swap-size-mb: # optional, default is 4096
    # Create the LVM disk images as sparse files, making the space required for the LVM image files *appear* unused on the
    overprovision-lvm: # optional, default is false
    # Absolute path to the mount point where the build space will be available, defaults to $GITHUB_WORKSPACE if unset.
    build-mount-path: # optional
    # Ownership of the mount point path, defaults to standard "runner" user and group.
    build-mount-path-ownership: # optional, default is runner:runner
    # Absolute file path for the LVM image created on the root filesystem, the default is usually fine.
    pv-loop-path: # optional, default is /pv.img
    # Absolute file path for the LVM image created on the temp filesystem, the default is usually fine. Must reside on /mnt
    tmp-pv-loop-path: # optional, default is /mnt/tmp-pv.img
    # Removes .NET runtime and libraries. (frees ~17 GB)
    remove-dotnet: # optional, default is false
    # Removes Android SDKs and Tools. (frees ~11 GB)
    remove-android: # optional, default is false
    # Removes GHC (Haskell) artifacts. (frees ~2.7 GB)
    remove-haskell: # optional, default is false
    # Removes CodeQL Action Bundles. (frees ~5.4 GB)
    remove-codeql: # optional, default is false
    # Removes cached Docker images. (frees ~3 GB)
    remove-docker-images: # optional, default is false
          
